AllCops:
  DisplayCopNames: true
  Include:
    - '**/Gemfile'
    - '**/Rakefile'
    - '**/Guardfile'
  Exclude:
   - 'bin/*'
   - 'db/schema.rb'
   - 'vendor/bundle/**/*'
Documentation:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Metrics/AbcSize:
  Exclude:
    - 'db/migrate/**'
Metrics/BlockLength:
  Exclude:
    - config/environments/production.rb
    - '**/*_spec.rb'
Metrics/MethodLength:
  Exclude:
    - 'db/migrate/**'
Rails:
  Enabled: true
