sudo: false
language: ruby
cache: bundler
before_script:
  - psql -c 'create database split_test;' -U postgres
rvm:
  - 2.3.1
script:
  - bundle exec rubocop
  - bundle exec rspec
services:
  - postgresql
